/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.admin;

import javax.swing.table.DefaultTableModel;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.FileReader;
import gui.admin.AdminPage;
import javax.swing.JOptionPane;
import java.io.File;
import tuition.UserSession;
import gui.admin.AdminTutor;
import gui.admin.AdminCalendar;
import gui.main.LoginPage;


/**
 *
 * @author 60193
 */
public class AdminTutor extends javax.swing.JFrame {
    DefaultTableModel model;
          private String loggedInUser;
          private String currentUsername;
          
    /**
     * Creates new form AdminTutor
     */
    public AdminTutor(String username) {
        initComponents();
         this.loggedInUser = username;
         String name = UserSession.getUsername();
         lblName.setText(username); // ✅ this only displays username
         lblName.setText( UserSession.getUsername());
        model = (DefaultTableModel) jTable1.getModel();
        model = (DefaultTableModel) jTable1.getModel();
        String[] colHeading = {"User ID", "Username", "Full Name", "Password", "Email", "Phone Number", "Level", "Subject"};
        model.setColumnIdentifiers(colHeading);
        loadTutorTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        btnCalender = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfPhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        tfUserID = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfFullName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        cbLevel = new javax.swing.JComboBox<>();
        lblLevel = new javax.swing.JLabel();
        cbSubject = new javax.swing.JComboBox<>();
        lblSubjects = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 65, 88));

        Welcome.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 35)); // NOI18N
        Welcome.setForeground(new java.awt.Color(221, 168, 83));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Welcome.setText("Welcome,");

        lblName.setFont(new java.awt.Font("Segoe UI Variable", 2, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(199, 138, 59));
        lblName.setText("Name");

        jPanel3.setBackground(new java.awt.Color(175, 221, 255));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ATC_LOGO-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnCalender.setBackground(new java.awt.Color(102, 102, 102));
        btnCalender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCalender.setForeground(new java.awt.Color(255, 255, 255));
        btnCalender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/admin/icons8-desk-calender-16.png"))); // NOI18N
        btnCalender.setText("Calender");
        btnCalender.setBorder(null);
        btnCalender.setContentAreaFilled(false);
        btnCalender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCalender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCalender.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalenderActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(102, 102, 102));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\60193\\OneDrive\\Documents\\NetBeansProjects\\TuitionManagementSystem\\images\\icons8-home-16.png")); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHome)
                .addGap(30, 30, 30)
                .addComponent(btnCalender)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(161, 179, 203));

        tfPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneNumberActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Email :");

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number :");

        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tfUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserIDActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setText("Tutor Data Management");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("UserID :");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Username :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Full Name :");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Password :");

        btnBack.setBackground(new java.awt.Color(161, 179, 203));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons8-go-back.gif"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Form 1", "Form 2", "Form 3", "Form 4","Form 5" }));
        cbLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLevelActionPerformed(evt);
            }
        });

        lblLevel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLevel.setText("Level :");

        cbSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mathematics", "Bahasa Melayu", "English", "Geography","Science", "Sejarah"}));
        cbSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubjectActionPerformed(evt);
            }
        });

        lblSubjects.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSubjects.setText("Subjects :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLevel))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubjects))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(delete)
                            .addComponent(edit)
                            .addComponent(register))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneNumberActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
    // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    String[] colHeading = {"User ID", "Username", "Full Name", "Password", "Email", "Phone Number", "Level", "Subject"};
    model.setColumnIdentifiers(colHeading);

    String userId = tfUserID.getText().trim();
    String username = tfUserName.getText().trim();
    String fullName = tfFullName.getText().trim();
    String password = tfPassword.getText().trim();
    String email = tfEmail.getText().trim();
    String phone = tfPhoneNumber.getText().trim();
    String level = cbLevel.getSelectedItem().toString();         // added line
    String subject = cbSubject.getSelectedItem().toString();     // added line

    if (userId.isEmpty() || username.isEmpty() || fullName.isEmpty() || password.isEmpty() || email.isEmpty() || phone.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields!");
        return;
    }

    try (BufferedWriter writer = new BufferedWriter(new FileWriter("assign_tutors.txt", true))) {
        writer.write(userId + "," + username + "," + fullName + "," + password + "," + email + "," + phone + "," + level + "," + subject);
        writer.newLine();

        JOptionPane.showMessageDialog(this, "Tutor registered successfully!");
        clearForm();
        loadTutorTable(); // if this reloads the JTable below
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving tutor data.");
}
    
    

//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//            String [ ] colHeading = {"User ID","User Name", "Full Name","Password","Email","Phone Number"};
//            model.setColumnIdentifiers(colHeading);
//
//        String userid = tfUserID.getText().trim();
//        String username = tfUserName.getText().trim();
//        String fullName = tfFullName.getText().trim();
//        String password = tfPassword.getText().trim();
//        String email = tfEmail.getText().trim();
//        String phone = tfPhoneNumber.getText().trim();
//
//        if (userid.isEmpty() || username.isEmpty() || fullName.isEmpty() || password.isEmpty() || email.isEmpty() || phone.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Please fill in all fields!");
//            return;
//        }
////
////       String dataRow [ ] = {tfUserID.getText(),tfUserName.getText(),tfFullName.getText(),tfPassword.getText(),tfEmail.getText(),tfPhoneNumber.getText()};
////       model.addRow(dataRow);
//
//        try (BufferedWriter writer = new BufferedWriter(new FileWriter("data/tutors.txt", true))) {
//            writer.write(userid + "," + username + "," + fullName + "," + password + "," + email + "," + phone);
//            writer.newLine();
//            JOptionPane.showMessageDialog(this, "Tutor registered successfully!");
//            clearForm(); 
//            loadTutorTable(); 
//        } catch (IOException e) {
//            JOptionPane.showMessageDialog(this, "Error saving tutor data.");
//        }
//    }
//    
//    private void clearForm() {
//        tfUserID.setText("");
//        tfUserName.setText("");
//        tfFullName.setText("");
//        tfPassword.setText("");
//        tfEmail.setText("");
//        tfPhoneNumber.setText("");
    }//GEN-LAST:event_registerActionPerformed

    
    private void loadTutorTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // clear existing rows

    try (BufferedReader reader = new BufferedReader(new FileReader("assign_tutors.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(",");

            if (data.length == 8) { // ✅ exactly 8 fields
                model.addRow(new Object[]{
                    data[0], data[1], data[2], data[3],
                    data[4], data[5], data[6], data[7]
                });
            } else {
                System.out.println("Skipping line due to invalid format: " + line); // for debugging
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error loading tutor data.");
}

//    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//    model.setRowCount(0); // clear existing rows
//    
//
//    try (BufferedReader reader = new BufferedReader(new FileReader("assign_tutors.txt"))) {
//        String line;
//        while ((line = reader.readLine()) != null) {
////            String[] data = line.split(",");
//String[] data = line.split(",");
//model.addRow(new Object[]{data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7]});
//            if (data.length >= 8) {
//                model.addRow(data); // add each row of tutor data
//            }
//        }
//    } catch (IOException e) {
//        JOptionPane.showMessageDialog(this, "Error loading tutor data.");
//    }
}

//    model.setRowCount(0); // Clear existing data in the table
//    File file = new File("data/tutors.txt");
//    
//
//    try (BufferedReader reader = new BufferedReader(new FileReader("data/tutors.txt"))) {
//        String line;
//        while ((line = reader.readLine()) != null) {
//            String[] data = line.split(",");
//            model.addRow(data); // Add data row to the table
//        }
//    } catch (IOException e) {
//        e.printStackTrace();
//}
 
    
    private void clearForm() {
    tfUserID.setText("");
    tfUserName.setText("");
    tfFullName.setText("");
    tfPassword.setText("");
    tfEmail.setText("");
    tfPhoneNumber.setText("");
    cbLevel.setSelectedIndex(0);     // Reset Level combo box
    cbSubject.setSelectedIndex(0);   // Reset Subject combo box
}

//        String line;
//        boolean skipHeader = true;
//
//        while ((line = reader.readLine()) != null) {
//            if (skipHeader) {
//                skipHeader = false;
//                continue; // skip first line (header)
//            }
//
//            String[] data = line.split(",");
//            if (data.length == 5) {
//                model.addRow(data);
//            }
//        }
//    } catch (IOException e) {
//        JOptionPane.showMessageDialog(this, "Error loading tutor data.");
//    }

    
    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Update JTable with new values from text fields
        model.setValueAt(tfUserID.getText(), selectedRow, 0);
        model.setValueAt(tfUserName.getText(), selectedRow, 1);
        model.setValueAt(tfFullName.getText(), selectedRow, 2);
        model.setValueAt(tfPassword.getText(), selectedRow, 3);
        model.setValueAt(tfEmail.getText(), selectedRow, 4);
        model.setValueAt(tfPhoneNumber.getText(), selectedRow, 5);
        model.setValueAt(cbLevel.getSelectedItem().toString(), selectedRow, 6);
model.setValueAt(cbSubject.getSelectedItem().toString(), selectedRow, 7);


        // Rewrite the file
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("data/assign_tutors.txt"))) {
            for (int i = 0; i < model.getRowCount(); i++) {
                writer.write(model.getValueAt(i, 0).toString() + "," +
                model.getValueAt(i, 0).toString() + "," +
                model.getValueAt(i, 1).toString() + "," +
                model.getValueAt(i, 2).toString() + "," +
                model.getValueAt(i, 3).toString() + "," +
                model.getValueAt(i, 4).toString() + "," +
                model.getValueAt(i, 5).toString() + "," +
                model.getValueAt(i, 6).toString() + "," +
                model.getValueAt(i, 7).toString());
                writer.newLine();
            }

            JOptionPane.showMessageDialog(this, "Tutor data updated successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving updated data.");
        }

        btnSave.setEnabled(false); // Disable button after save
    } else {
        JOptionPane.showMessageDialog(this, "No row selected to save.");
    }

//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        btnSave.setEnabled(false) ;
//        int sRow = jTable1.getSelectedRow() ;
//        model.setValueAt(tfUserID.getText(), sRow, 0) ;
//        model.setValueAt(tfUserName.getText(), sRow, 1) ;
//        model.setValueAt(tfFullName.getText(), sRow, 2) ;
//        model.setValueAt(tfPassword.getText(), sRow, 3) ;
//        model.setValueAt(tfEmail.getText(), sRow, 4) ;
//        model.setValueAt(tfPhoneNumber.getText(), sRow, 5) ;
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tfUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserIDActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        //TODO add your handling code here:
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Update JTable with new values from text fields
        model.setValueAt(tfUserID.getText(), selectedRow, 0);
        model.setValueAt(tfUserName.getText(), selectedRow, 1);
        model.setValueAt(tfFullName.getText(), selectedRow, 2);
        model.setValueAt(tfPassword.getText(), selectedRow, 3);
        model.setValueAt(tfEmail.getText(), selectedRow, 4);
        model.setValueAt(tfPhoneNumber.getText(), selectedRow, 5);
        model.setValueAt(cbLevel.getSelectedItem().toString(), selectedRow, 6);   // new
        model.setValueAt(cbSubject.getSelectedItem().toString(), selectedRow, 7); // new

        // Rewrite the file with all rows
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("assign_tutors.txt"))) {
            for (int i = 0; i < model.getRowCount(); i++) {
                writer.write(model.getValueAt(i, 0).toString() + "," +
                             model.getValueAt(i, 1).toString() + "," +
                             model.getValueAt(i, 2).toString() + "," +
                             model.getValueAt(i, 3).toString() + "," +
                             model.getValueAt(i, 4).toString() + "," +
                             model.getValueAt(i, 5).toString() + "," +
                             model.getValueAt(i, 6).toString() + "," +
                             model.getValueAt(i, 7).toString());
                writer.newLine();
            }

            JOptionPane.showMessageDialog(this, "Tutor data updated successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving updated data.");
        }

        btnSave.setEnabled(false); // Disable button after save
    } else {
        JOptionPane.showMessageDialog(this, "No row selected to save.");
}

//    int selectedRow = jTable1.getSelectedRow();
//    if (selectedRow != -1) {
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        model.removeRow(selectedRow);
//
//        // Rewrite file after deletion
//        try (BufferedWriter writer = new BufferedWriter(new FileWriter("data/tutors.txt"))) {
//            for (int i = 0; i < model.getRowCount(); i++) {
//                for (int j = 0; j < model.getColumnCount(); j++) {
//                    writer.write(model.getValueAt(i, j).toString());
//                    if (j != model.getColumnCount() - 1) writer.write(",");
//                }
//                writer.newLine();
//            }
//            JOptionPane.showMessageDialog(this, "Tutor deleted successfully!");
//        } catch (IOException e) {
//            JOptionPane.showMessageDialog(this, "Error deleting tutor.");
//        }
//    } else {
//        JOptionPane.showMessageDialog(this, "Please select a row to delete.");
//    }
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {
        tfUserID.setText(jTable1.getValueAt(selectedRow, 0).toString());
        tfUserName.setText(jTable1.getValueAt(selectedRow, 1).toString());
        tfFullName.setText(jTable1.getValueAt(selectedRow, 2).toString());
        tfPassword.setText(jTable1.getValueAt(selectedRow, 3).toString());
        tfEmail.setText(jTable1.getValueAt(selectedRow, 4).toString());
        tfPhoneNumber.setText(jTable1.getValueAt(selectedRow, 5).toString());
        cbLevel.setSelectedItem(jTable1.getValueAt(selectedRow, 6).toString());
        cbSubject.setSelectedItem(jTable1.getValueAt(selectedRow, 7).toString());


        // ✅ Add this line here to enable Save button
        btnSave.setEnabled(true);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to edit.");
    }



//        // Optional: disable UserID editing
//        tfUserID.setEnabled(false);

//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        btnSave.setEnabled(true);
//        int sRow = jTable1.getSelectedRow() ;
//        //        System.out.println("Selected Row: "+sRow);
//        tfUserID.setText(model.getValueAt(sRow, 0).toString()) ;
//        tfUserName.setText(model.getValueAt(sRow, 1).toString()) ;
//        tfFullName.setText(model.getValueAt(sRow, 2).toString()) ;
//        tfPassword.setText(model.getValueAt(sRow, 3).toString()) ;
//        tfEmail.setText(model.getValueAt(sRow, 4).toString()) ;
//        tfPhoneNumber.setText(model.getValueAt(sRow, 5).toString()) ;
    }//GEN-LAST:event_editActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminPage().setVisible(true); // Go back to Admin Dashboard
        this.dispose(); // Close the current Tutor page

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalenderActionPerformed
        // TODO add your handling code here:
        new AdminCalendar().setVisible(true);
    }//GEN-LAST:event_btnCalenderActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void cbLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLevelActionPerformed

    private void cbSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSubjectActionPerformed

    /**
     * @param args the command line arguments
     */
            public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(AdminTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(AdminTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(AdminTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(AdminTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    new AdminTutor(UserSession.getUsername()).setVisible(true);
                    }
                });
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalender;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbLevel;
    private javax.swing.JComboBox<String> cbSubject;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSubjects;
    private javax.swing.JButton register;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfPhoneNumber;
    private javax.swing.JTextField tfUserID;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables

}