/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.main;

import java.io.*;
import java.util.Scanner;
import javax.swing.JOptionPane;
import tuition.Utils;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import gui.admin.AdminPage;
import gui.tutors.TutorPage;
import gui.receptionist.ReceptionistPage;
import gui.student.StudentPage;
import tuition.UserSession;



/**
 *
 * @author 60193
 */
public class LoginPage extends javax.swing.JFrame {
    private String loggedInUser;
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        String currentUsername = UserSession.getUsername();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginpage = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        usernama = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        forgetpass = new javax.swing.JLabel();
        chkRememberMe = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginpage.setFont(new java.awt.Font("Times New Roman", 2, 38)); // NOI18N
        loginpage.setText("Login Page");

        tfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserNameActionPerformed(evt);
            }
        });

        usernama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usernama.setForeground(new java.awt.Color(0, 51, 153));
        usernama.setText("Username :");

        password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(0, 51, 153));
        password.setText("Password :");

        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        tittle.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        tittle.setForeground(new java.awt.Color(51, 51, 51));
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("ATC Management System");

        forgetpass.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        forgetpass.setText("Forget Password?");

        chkRememberMe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkRememberMe.setText("Remember me");
        chkRememberMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRememberMeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ATC_LOGO-removebg-preview.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        jLabel2.setText("© 2025 Advanced Tuition Centre (ATC) - All Rights Reserved ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1068, 1068, 1068)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(542, 542, 542)
                        .addComponent(loginpage, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(forgetpass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chkRememberMe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password)
                                    .addComponent(usernama))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfUserName)
                                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginpage)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernama))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkRememberMe)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(forgetpass)))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
String Username = tfUserName.getText().trim();
UserSession.setUsername(Username);
String Password = new String(tfPassword.getPassword()).trim();

boolean isLoggedIn = false;
String role = "";

try (BufferedReader reader = new BufferedReader(new FileReader("data/users.txt"))) {
    String line;
    while ((line = reader.readLine()) != null) {
        String[] parts = line.split(",");
        if (parts.length >= 3) {
            String fileUsername = parts[0].trim();
            String filePassword = parts[1].trim();
            String fileRole     = parts[2].trim();

            if (Username.equals(fileUsername) && Password.equals(filePassword)) {
                isLoggedIn = true;
                role = fileRole;
                break; // Exit loop once user is found
            }
        }
    }
} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Error reading users.txt:\n" + e.getMessage());
}

// ✅ Now handle result AFTER the loop
if (isLoggedIn) {
    JOptionPane.showMessageDialog(this, "Login successful as " + role + "!");

    switch (role.toLowerCase()) {
        case "admin":
            new AdminPage().setVisible(true);
            break;
        case "tutor":
            new TutorPage().setVisible(true);
            break;
        case "receptionist":
            new ReceptionistPage().setVisible(true);
            break;
        case "student":
            new StudentPage().setVisible(true);
            break;
        default:
            JOptionPane.showMessageDialog(this, "Unknown role: " + role);
            break;
    }

    this.dispose(); // Close login window
} else {
    JOptionPane.showMessageDialog(this, "Invalid username or password.");
    }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void tfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserNameActionPerformed
        // TODO add your handling code here:
        String currentUsername = tfUserName.getText().trim();    // your login field
        String currentPassword = tfPassword.getText().trim();
    }//GEN-LAST:event_tfUserNameActionPerformed

    private void chkRememberMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRememberMeActionPerformed
        // TODO add your handling code here:
            if (chkRememberMe.isSelected()) {
                String currentusername = tfUserName.getText().trim();
                String currentpassword = new String(tfPassword.getPassword()).trim();

                if (!currentusername.isEmpty() && !currentpassword.isEmpty()) {
                    try {
                        File rememberFile = new File("data/rememberme.txt");
                        BufferedWriter writer = new BufferedWriter(new FileWriter(rememberFile));
                        writer.write(currentusername + "," + password);
                        writer.close();
                        JOptionPane.showMessageDialog(this, "Credentials will be remembered ✅");
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(this, "Failed to save Remember Me file ❌\n" + e.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Please fill both username and password fields first.");
                    chkRememberMe.setSelected(false); // auto-uncheck if fields empty
                }
            } else {
                // If user unchecks it, remove the file
                File rememberFile = new File("data/rememberme.txt");
                if (rememberFile.exists()) {
                    rememberFile.delete();
                    JOptionPane.showMessageDialog(this, "Remember Me disabled. Info cleared ✅");
                }
           }
    }//GEN-LAST:event_chkRememberMeActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkRememberMe;
    private javax.swing.JLabel forgetpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel loginpage;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUserName;
    private javax.swing.JLabel tittle;
    private javax.swing.JLabel usernama;
    // End of variables declaration//GEN-END:variables
}

