/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.student;

import java.io.*;
import gui.student.StudentPage;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showInputDialog;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.File;
import javax.swing.DefaultListModel;
import tuition.UserSession;
import gui.admin.AdminCalendar;


/**
 *
 * @author 60193
 */

public class StudentClass extends javax.swing.JFrame {
        private String currentUsername;
        private String loggedInUser;
        private DefaultTableModel modelViewPayment;
        
    
    /**
     * Creates new form StudentClass
     */

//        private javax.swing.JTable tblViewPayment;
//        private DefaultTableModel modelViewPayment;

        
          public StudentClass() {
                initComponents();
          }
          
    
    public StudentClass(String username) {
        initComponents();
       this.loggedInUser = username;
        String name = UserSession.getUsername();
        lblName.setText(username); // ✅ this only displays username
        lblName.setText( UserSession.getUsername());
        tblViewPayment.setModel(new DefaultTableModel(new Object[]{"Date","Subjects", "Total Fee","Amount Paid", "Balance"}, 0));
        modelViewPayment = (DefaultTableModel) tblViewPayment.getModel(); // spacing issue too!


//        this.currentStudentId=studentId;

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        btnCalender = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnRemovePending = new javax.swing.JButton();
        btnRequestSubject = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewPayment = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 65, 88));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Welcome.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 35)); // NOI18N
        Welcome.setForeground(new java.awt.Color(221, 168, 83));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Welcome.setText("Welcome,");

        lblName.setFont(new java.awt.Font("Segoe UI Variable", 2, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(199, 138, 59));
        lblName.setText("Name");

        jPanel3.setBackground(new java.awt.Color(175, 221, 255));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ATC_LOGO-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnCalender.setBackground(new java.awt.Color(102, 102, 102));
        btnCalender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCalender.setForeground(new java.awt.Color(255, 255, 255));
        btnCalender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/admin/icons8-desk-calender-16.png"))); // NOI18N
        btnCalender.setText("Calender");
        btnCalender.setBorder(null);
        btnCalender.setContentAreaFilled(false);
        btnCalender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCalender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCalender.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalenderActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(102, 102, 102));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\60193\\OneDrive\\Documents\\NetBeansProjects\\TuitionManagementSystem\\images\\icons8-home-16.png")); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHome)
                .addGap(30, 30, 30)
                .addComponent(btnCalender)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(161, 179, 203));

        btnBack2.setBackground(new java.awt.Color(161, 179, 203));
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons8-go-back.gif"))); // NOI18N
        btnBack2.setBorder(null);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnRemovePending.setText("Remove Pending");
        btnRemovePending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePendingActionPerformed(evt);
            }
        });

        btnRequestSubject.setText("Request Subject");
        btnRequestSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestSubjectActionPerformed(evt);
            }
        });

        tblViewPayment.setBackground(new java.awt.Color(196, 225, 246));
        tblViewPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblViewPayment);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack2))
                        .addGap(10, 10, 10)
                        .addComponent(btnRemovePending, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnRequestSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack2)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnRemovePending)
                    .addComponent(btnRequestSubject))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        new StudentPage().setVisible(true); // Go back to Student Dashboard
        this.dispose(); // Close the current Tutor page
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:   
    String username = lblName.getText().trim(); // Get current student username
    DefaultTableModel model = (DefaultTableModel) tblViewPayment.getModel();
    model.setRowCount(0); // clear previous rows

    String[] subjects = null;
    int subjectCount = 0;

    // Step 1: Read from students.txt to get subjects
    try (BufferedReader br = new BufferedReader(new FileReader("students.txt"))) {
        String line;
        boolean found = false;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");
            if (data.length >= 12 && data[1].equalsIgnoreCase(username)) {
                subjects = new String[]{data[9], data[10], data[11]};
                subjectCount = subjects.length;
                found = true;
                break;
            }
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "No subjects found for user.");
            return;
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Student file not found.");
        return;
    }

    // Step 2: Read from payments.txt to get amount paid and date
    double amountPaid = 0.0;
    String paymentDate = "N/A";
    try (BufferedReader br = new BufferedReader(new FileReader("payments.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");
            if (data.length >= 3 && data[0].equalsIgnoreCase(username)) {
                amountPaid = Double.parseDouble(data[1]);
                paymentDate = data[3];
                break;
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Payment file not found.");
        return;
    }

    // Step 3: Calculate total fee (Assume RM125 per subject)
    int totalFee = subjectCount * 125;
    double balance = totalFee - amountPaid;

    // Step 4: Format subject list (each in new line)
    String subjectList = "";
    for (String s : subjects) {
        if (s != null && !s.trim().isEmpty()) {
            subjectList += s + "\n";
        }
    }

    // Step 5: Add to table
    model.addRow(new Object[]{
        paymentDate,
        subjectList.trim(),
        "RM " + totalFee,
        "RM " + amountPaid,
        "RM " + balance
    });
    }//GEN-LAST:event_btnViewActionPerformed

//        DefaultTableModel model = (DefaultTableModel) tblViewPayment.getModel();
//    model.setRowCount(0); // Clear table before loading new data
//
//    String username = UserSession.getUsername();
//    File paymentFile = new File("data/payments.txt");
//    File studentFile = new File("data/students.txt");
//
//    if (!paymentFile.exists() || !studentFile.exists()) {
//        JOptionPane.showMessageDialog(this, "Payment or student file not found.");
//        return;
//    }
//
//    String subjects = "";
//    double totalPaid = 0;
//    String date = "";
//
//    try (BufferedReader br = new BufferedReader(new FileReader(paymentFile))) {
//        String line;
//        while ((line = br.readLine()) != null) {
//            String[] parts = line.split(",");
//            if (parts[0].equalsIgnoreCase(username)) {
//                totalPaid = Double.parseDouble(parts[1]);
//                date = parts[3];
//                break;
//            }
//        }
//    } catch (IOException | NumberFormatException e) {
//        JOptionPane.showMessageDialog(this, "Error reading payment file.");
//        e.printStackTrace();
//        return;
//    }
//
//    try (BufferedReader br = new BufferedReader(new FileReader(studentFile))) {
//        String line;
//        while ((line = br.readLine()) != null) {
//            String[] parts = line.split("\\|");
//            if (parts.length >= 4 && parts[0].equalsIgnoreCase(username)) {
//                subjects = parts[3]; // Assuming subjects are in 4th column (index 3)
//                break;
//            }
//        }
//    } catch (IOException e) {
//        JOptionPane.showMessageDialog(this, "Error reading student file.");
//        e.printStackTrace();
//        return;
//    }
//
//    if (subjects.isEmpty()) {
//        JOptionPane.showMessageDialog(this, "No subjects found for user.");
//        return;
//    }
//
//    String[] subjectList = subjects.split(";");
//    double feePerSubject = 100.0;
//    double totalFee = subjectList.length * feePerSubject;
//
//    for (String subject : subjectList) {
//        double paidPerSubject = totalPaid / subjectList.length;
//        double balance = feePerSubject - paidPerSubject;
//
//        model.addRow(new Object[]{
//            date,
//            subject.trim(),
//            "RM " + String.format("%.2f", feePerSubject),
//            "RM " + String.format("%.2f", paidPerSubject),
//            "RM " + String.format("%.2f", balance)
//        });
//    }
    
    private void btnRemovePendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePendingActionPerformed
        // TODO add your handling code here:
            String username = UserSession.getUsername();

            File inputFile = new File("data/pending_requests.txt");
            File tempFile = new File("data/temp_requests.txt");

            try (
                BufferedReader reader = new BufferedReader(new FileReader(inputFile));
                BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));
            ) {
                String currentLine;

                while ((currentLine = reader.readLine()) != null) {
                    // Skip the lines belonging to this user
                    if (!currentLine.startsWith(username + ",")) {
                        writer.write(currentLine);
                        writer.newLine();
                    }
                }

                reader.close();
                writer.close();

                if (inputFile.delete()) {
                    tempFile.renameTo(inputFile);
                    JOptionPane.showMessageDialog(null, "Pending request removed!");
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
    }//GEN-LAST:event_btnRemovePendingActionPerformed

    private void btnRequestSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestSubjectActionPerformed
        // TODO add your handling code here:
            String username = UserSession.getUsername();
            String requestedSubject = JOptionPane.showInputDialog(null, "Enter the subject you want to request:");

            try (BufferedWriter writer = new BufferedWriter(new FileWriter("data/pending_requests.txt", true))) {
                writer.write(username + "," + requestedSubject);
                writer.newLine();
                writer.close();
                JOptionPane.showMessageDialog(null, "Request submitted!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
    }//GEN-LAST:event_btnRequestSubjectActionPerformed

    private void btnCalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalenderActionPerformed
        // TODO add your handling code here:
        new AdminCalendar().setVisible(true);
    }//GEN-LAST:event_btnCalenderActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentClass(UserSession.getUsername()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnCalender;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRemovePending;
    private javax.swing.JButton btnRequestSubject;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblViewPayment;
    // End of variables declaration//GEN-END:variables
}
